[tool.poetry]
name = "vits-web-demo"
version = "0.1.0"
description = ""
authors = ["ccds"]
readme = "README.md"
packages = [{include = "vits_web_demo"}]



[tool.poetry.dependencies]
python = "^3.9"
pyopenjtalk = "^0.3.0"
torch = {url="https://download.pytorch.org/whl/cpu/torch-1.13.0%2Bcpu-cp39-cp39-linux_x86_64.whl"}
typing-extensions = "^4.4.0"
gradio = "^3.10.1"
librosa = "^0.9.2"
unidecode = "^1.3.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
