
config=https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9zdHV4aWRpYW5lZHVjbi1teS5zaGFyZXBvaW50LmNvbS86dTovZy9wZXJzb25hbC8yMTAwOTIwMDQzMV9zdHVfeGlkaWFuX2VkdV9jbi9FWHpHaDVFQWw1dEJsWU1CaDliWlZqVUJWNklSWThJSkY5aGxmVXdPWHNWMHdBP2U9NHpkUWp2.jpg


model=https://link.jscdn.cn/sharepoint/aHR0cHM6Ly9zdHV4aWRpYW5lZHVjbi1teS5zaGFyZXBvaW50LmNvbS86dTovZy9wZXJzb25hbC8yMTAwOTIwMDQzMV9zdHVfeGlkaWFuX2VkdV9jbi9FYnpzUm80Q0NneEhsdFpHaloxMXN3RUJ2VVBrZTBWMmdZQUZicGZlb2preHp3P2U9UDFLNEdh.jpg

wget $model -O ~/.model/model.pth
wget $config -O ~/.model/config.json

