FROM python:3.9.13-buster

WORKDIR /workspace/
COPY . /workspace/


ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"



RUN mv asset/script/run.sh ./run.sh && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y  --no-install-recommends libsndfile1-dev cmake libsndfile1 espeak build-essential && \
    python3 -m pip install --upgrade pip && \
    pip3 install -r requirements.txt && \
    python3 init_jptalk.py && \
    cd monotonic_align && \
    python3 setup.py build_ext --inplace  


# CMD ["python3","app.py","-m /mydata/model.pth","-c /mydata/config.json"]