name: onnx_docker

on:
  workflow_dispatch:


env:
  # 设置 docker 镜像名
  IMAGE_NAME: vits_demo
  VERSION: onnx

jobs:
  push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # 构建镜像，指定镜像名
      
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }} 
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
        # 登录到 dockerhub，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器，添加方法见下图。
     

      - name: Push image
        run: |
          # 拼接镜像 id，这个镜像 id 就是在使用 docker 镜像时 pull 后面的名字。
          
          IMAGE_ID=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME

          # 将所有的大写字母转为小写
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

      
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          # 设置镜像 id 和版本号
          
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION

          # 进行 push
          docker push $IMAGE_ID:$VERSION
