name: ci

on:
  workflow_dispatch:


jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - run: echo  ${{ secrets.DOCKERHUB_USERNAME }} 
      - run : echo ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
     
