name: upload wheel

on:
  workflow_dispatch:



jobs:
  upload_wheel:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]

    steps:
      - uses: actions/checkout@v3
        with:
          repository: r9y9/pyopenjtalk
          ref: v0.3.0
          submodules: true
          # token: ${{ secrets.GITHUB_TOKEN }}
          # token: "sad"

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          # cache: 'pip' # caching pip dependencies

      - name: init wheel
        run: pip install wheel

      - name: install pyopenjtalk
        run: |
          pip wheel --wheel-dir=./wheel ./ 
          curl -o zip_wheel.py https://raw.githubusercontent.com/chocolatedesue/vits_web_demo/test/test/zip_wheel.py 
          python zip_wheel.py --wheel_dir ./wheel --zip_file ${{ matrix.os }}-wheel.zip
        


      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          # files: {{matrix.os}}wheel.tar.gz
          files: ${{ matrix.os }}-wheel.zip
          tag_name: wheel_build
          name: wheel_build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
